# Update Wordpress:php7.2-fpm Software repository
FROM wordpress:php7.3-fpm
# Update Alpine Software
ADD ./uploads.ini /usr/local/etc/php/conf.d
RUN apt-get update && apt-get install -y --no-install-recommends \
&& pecl install redis && docker-php-ext-enable redis \
&& rm -rf /var/lib/apt/lists/*